# @package _group_
max_iterations: 2
checkpoint_frequency: 1

batch_size: 4
val_split: 0 # 0 or null - no split
val_batch_size: 0 # null - full
test_batch_size: 1 # null - full
take_batch: 5  # null - full
seed: 12344321

learning_rate: 0.00001
early_stop_patience: 10
early_stop_metric: loss
early_stop_min_delta_patience: null
early_stop_min_delta: null
img_preview_threshold: 1
max_time_s: null
no_shuffle: false
target_loss: 0.000000000000001
show_gradients: false

#optimizer: 
#  _target_: tensorflow.keras.optimizers.RMSprop