# @package _group_
max_iterations: 2
checkpoint_frequency: 1

batch_size: 4
val_split: 0
val_batch_size: 0
test_batch_size: 1
take_batch: 5

learning_rate: 0.00001
early_stop_patience: 4
img_preview_threshold: 1
max_time_s: null
no_shuffle: false
target_loss: 0.000000000000001
show_gradients: false