
defaults:
  - runner: ray
  - model: autoenc_deconv
  - training: default
  - dataset: sn3
  - runner/trainable@runner.trainable: default

preview_dataset: false
prev_ds_path_p1: __dataset3/novak
prev_ds_path_p2: __dataset3/serena